import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./Navbar";
import BootstrapClient from "./components/BootstrapClient";
import ReduxProvider from "./components/ReduxProvider";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });
import { Poppins } from "next/font/google";
import { Provider } from "react-redux";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProvider>{children}</ReduxProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
