import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./Navbar";
import BootstrapClient from "./components/BootstrapClient";
import ReduxProvider from "./components/ReduxProvider";
import "react-toastify/dist/ReactToastify.css";
import { Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "GIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
